spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/kotlin-ddd
      database: kotlin-ddd
  application:
    name: kotlin-functional-ddd

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  show-actuator: false